// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN5eK-kx3Wr2VzNXJvihYjYtccaQuBUlI',
    appId: '1:769137324877:web:d1febf0c5f8f62ce03fd04',
    messagingSenderId: '769137324877',
    projectId: 'intellicart-9400a',
    authDomain: 'intellicart-9400a.firebaseapp.com',
    storageBucket: 'intellicart-9400a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnX5bVZR_Xk21oEu1xYdqcokQR-67z3EA',
    appId: '1:769137324877:android:438af3547919498f03fd04',
    messagingSenderId: '769137324877',
    projectId: 'intellicart-9400a',
    storageBucket: 'intellicart-9400a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqJURLD7v_iVEZN2oE_BPJ31M9NaVnP24',
    appId: '1:769137324877:ios:95f763f0b38241da03fd04',
    messagingSenderId: '769137324877',
    projectId: 'intellicart-9400a',
    storageBucket: 'intellicart-9400a.appspot.com',
    iosBundleId: 'com.example.intellicart',
  );
}
