// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNcH5L6Ev5trE8C5Ifihm9670pi4DKP3I',
    appId: '1:454647962462:web:a7ca318a4f2cd5048a4dcf',
    messagingSenderId: '454647962462',
    projectId: 'fyp-intellicart',
    authDomain: 'fyp-intellicart.firebaseapp.com',
    storageBucket: 'fyp-intellicart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWC_rm52n5zxb1SPiEDUEu2y-P0Gfj8V8',
    appId: '1:454647962462:android:d7ec561bf2e88d698a4dcf',
    messagingSenderId: '454647962462',
    projectId: 'fyp-intellicart',
    storageBucket: 'fyp-intellicart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJBaCF3FPKiv-FxC8_3vjhN3NDWNnLsgk',
    appId: '1:454647962462:ios:012716dce4475f468a4dcf',
    messagingSenderId: '454647962462',
    projectId: 'fyp-intellicart',
    storageBucket: 'fyp-intellicart.appspot.com',
    iosBundleId: 'com.example.intellicart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJBaCF3FPKiv-FxC8_3vjhN3NDWNnLsgk',
    appId: '1:454647962462:ios:9f6cc849762ba2698a4dcf',
    messagingSenderId: '454647962462',
    projectId: 'fyp-intellicart',
    storageBucket: 'fyp-intellicart.appspot.com',
    iosBundleId: 'com.example.intellicart.RunnerTests',
  );
}
